#!/bin/sh
set -e

infp="${INSOMNIA_DIR}/in"
if [ ! -p "${infp}" ]; then
	echo "'${infp}' isn't a FIFO or does not exist" 1>&2
	exit 1
fi

nickfp="${INSOMNIA_DIR}/usr"
[ -S "${nickfp}" ] || unset -v nickfp

histdir="${XDG_DATA_HOME:-$HOME/.local/share}/insomnia"
mkdir -p "${histdir}"

name="$(insomnia-name)"
input -w ${nickfp:+-c "insomnia-unix '${nickfp}'"} \
		-h "${histdir}/input-history" \
		-p "[${name:-(status)}] " \
		| while read -r line; do
	# TODO: Implement shortcut commmands, e.g. `/j <CHAN>`.
	[ -p "${infp}" ] && printf "%s\n" "${line}" > "${infp}"
done
