#!/usr/bin/awk -f

/^[0-9]+ \*\*\* .+ has set the topic to: .*$/ {
	# XXX: The code here potentially reformats the topic
	topic = $9
	for (i = 10; i <= NF; i++)
		topic = topic " " $i

	# Append escape sequence for setting tmux pane title.
	$0 = $0 sprintf("\033]2;%s\033\\", topic)
}

{
	print
	fflush()
}
