#!/bin/sh

# This script reverse an `out` file. This allows finding the latest
# message of a certain type using grep(1), awk(1), sed(1), …

# There is actually no need to sort the `out` file by timestamp.
# Unfourtunatly, POSIX currently doesn't specify a command line utility
# for reversing an input stream. Therefore we are forced to use sort(1).
#
# This will change though: http://austingroupbugs.net/view.php
exec sort -k1 -r "${INSOMNIA_DIR}/out"
