#!/bin/sh
set -e

preamble() {
	echo "Input is send to the channel, prefix commands with a backslash."
}

infp="${INSOMNIA_DIR}/in"
if [ ! -p "${infp}" ]; then
	echo "'${infp}' isn't a FIFO or does not exist" 1>&2
	exit 1
fi

nickfp="${INSOMNIA_DIR}/usr"
[ -S "${nickfp}" ] || unset -v nickfp

name="${INSOMNIA_DIR##*/}"

preamble
input ${nickfp:+-c "insomnia-unix '${nickfp}'"} \
		-p "[${name:-(status)}] " \
		| while read -r line; do
	# TODO: Implement shortcut commmands, e.g. `/j <CHAN>`.
	preamble && printf "%s\n" "${line}" > "${infp}"
done
