#!/usr/bin/awk -f

BEGIN {
	FS=": "
}

/^[0-9]+ \[.+\] \*\*\* .+ has set the topic to: .*$/ {
	command = "xargs -I '{}' tmux rename-window '{}'"
	printf("%s\n", $2) | command
	close(command)
}

{
	print
}
