#!/bin/sh
set -e

outfp="${INSOMNIA_DIR}/out"
if [ ! -f "${outfp}" ]; then
	echo "'${outfp}' isn't a regular file or does not exist" 1>&2
	exit 1
fi

tail -n 128 -f "${outfp}" | \
	insomnia-track-topic | \
	insomnia-color | \
	insomnia-strftime
