#!/usr/bin/awk -f

BEGIN {
	idfp = ENVIRON["INSOMNIA_DIR"] "/id"
	getline name < idfp
	close(name)
}

function ischan(channel) {
	# This is a stripped down variant of IsValidChannel from girc
	# which only checks the first character to determine channels.

	first = substr(channel, 1, 1)
	return index("!#&*~+", first)
}

/^[0-9]* \[.+\] \(.+\) .+$/ {
	source = substr($3, 0, length($3) - 1)
	if (!ischan(source))
		source = substr($4, 2, length($4) - 2)

	if (source != name || name == "") {
		printf("%s\a\n", $0)
		fflush()
		next
	}
}

{
	print
	fflush()
}
