#!/bin/sh
set -e

infp="${INSOMNIA_DIR}/in"
if [ ! -p "${infp}" ]; then
	echo "'${infp}' isn't a FIFO or does not exist" 1>&2
	exit 1
fi

nickfp="${INSOMNIA_DIR}/usr"
[ -S "${nickfp}" ] || unset -v nickfp

name="$(insomnia-name)"
input ${nickfp:+-c "insomnia-unix '${nickfp}'"} \
		-p "[${name:-(status)}] " \
		| while read -r line; do
	# TODO: Implement shortcut commmands, e.g. `/j <CHAN>`.
	printf "%s\n" "${line}" > "${infp}"
done
