#!/bin/sh
set -e

outfp="${INSOMNIA_DIR}/out"
[ -e "${outfp}" ] || touch "${outfp}"

# Set tmux pane-title to topic
printf '\033]2;%s\033\\' "$(insomnia-topic)"

# Only highlight mentions in channels
[ -S "${INSOMNIA_DIR}/usr" ] && ischan=1

tail -n 128 -f "${outfp}" | \
	insomnia-track-topic | \
	insomnia-color -e ${ischan:+-m} | \
	insomnia-strip-bell | \
	insomnia-strftime
